// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package growlog_server

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GrowLogClient is the client API for GrowLog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrowLogClient interface {
	Register(ctx context.Context, in *RegistrationInfo, opts ...grpc.CallOption) (*User, error)
	Login(ctx context.Context, in *UserCredential, opts ...grpc.CallOption) (*User, error)
	InsertRow(ctx context.Context, in *TimeSeriesDatum, opts ...grpc.CallOption) (*empty.Empty, error)
	InsertRows(ctx context.Context, opts ...grpc.CallOption) (GrowLog_InsertRowsClient, error)
	Select(ctx context.Context, in *Filter, opts ...grpc.CallOption) (GrowLog_SelectClient, error)
}

type growLogClient struct {
	cc grpc.ClientConnInterface
}

func NewGrowLogClient(cc grpc.ClientConnInterface) GrowLogClient {
	return &growLogClient{cc}
}

func (c *growLogClient) Register(ctx context.Context, in *RegistrationInfo, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/proto.GrowLog/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *growLogClient) Login(ctx context.Context, in *UserCredential, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/proto.GrowLog/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *growLogClient) InsertRow(ctx context.Context, in *TimeSeriesDatum, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.GrowLog/InsertRow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *growLogClient) InsertRows(ctx context.Context, opts ...grpc.CallOption) (GrowLog_InsertRowsClient, error) {
	stream, err := c.cc.NewStream(ctx, &GrowLog_ServiceDesc.Streams[0], "/proto.GrowLog/InsertRows", opts...)
	if err != nil {
		return nil, err
	}
	x := &growLogInsertRowsClient{stream}
	return x, nil
}

type GrowLog_InsertRowsClient interface {
	Send(*TimeSeriesDatum) error
	CloseAndRecv() (*empty.Empty, error)
	grpc.ClientStream
}

type growLogInsertRowsClient struct {
	grpc.ClientStream
}

func (x *growLogInsertRowsClient) Send(m *TimeSeriesDatum) error {
	return x.ClientStream.SendMsg(m)
}

func (x *growLogInsertRowsClient) CloseAndRecv() (*empty.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(empty.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *growLogClient) Select(ctx context.Context, in *Filter, opts ...grpc.CallOption) (GrowLog_SelectClient, error) {
	stream, err := c.cc.NewStream(ctx, &GrowLog_ServiceDesc.Streams[1], "/proto.GrowLog/Select", opts...)
	if err != nil {
		return nil, err
	}
	x := &growLogSelectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GrowLog_SelectClient interface {
	Recv() (*DataPoint, error)
	grpc.ClientStream
}

type growLogSelectClient struct {
	grpc.ClientStream
}

func (x *growLogSelectClient) Recv() (*DataPoint, error) {
	m := new(DataPoint)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GrowLogServer is the server API for GrowLog service.
// All implementations must embed UnimplementedGrowLogServer
// for forward compatibility
type GrowLogServer interface {
	Register(context.Context, *RegistrationInfo) (*User, error)
	Login(context.Context, *UserCredential) (*User, error)
	InsertRow(context.Context, *TimeSeriesDatum) (*empty.Empty, error)
	InsertRows(GrowLog_InsertRowsServer) error
	Select(*Filter, GrowLog_SelectServer) error
	mustEmbedUnimplementedGrowLogServer()
}

// UnimplementedGrowLogServer must be embedded to have forward compatible implementations.
type UnimplementedGrowLogServer struct {
}

func (UnimplementedGrowLogServer) Register(context.Context, *RegistrationInfo) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedGrowLogServer) Login(context.Context, *UserCredential) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedGrowLogServer) InsertRow(context.Context, *TimeSeriesDatum) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertRow not implemented")
}
func (UnimplementedGrowLogServer) InsertRows(GrowLog_InsertRowsServer) error {
	return status.Errorf(codes.Unimplemented, "method InsertRows not implemented")
}
func (UnimplementedGrowLogServer) Select(*Filter, GrowLog_SelectServer) error {
	return status.Errorf(codes.Unimplemented, "method Select not implemented")
}
func (UnimplementedGrowLogServer) mustEmbedUnimplementedGrowLogServer() {}

// UnsafeGrowLogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrowLogServer will
// result in compilation errors.
type UnsafeGrowLogServer interface {
	mustEmbedUnimplementedGrowLogServer()
}

func RegisterGrowLogServer(s grpc.ServiceRegistrar, srv GrowLogServer) {
	s.RegisterService(&GrowLog_ServiceDesc, srv)
}

func _GrowLog_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrationInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrowLogServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GrowLog/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrowLogServer).Register(ctx, req.(*RegistrationInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrowLog_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCredential)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrowLogServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GrowLog/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrowLogServer).Login(ctx, req.(*UserCredential))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrowLog_InsertRow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeSeriesDatum)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrowLogServer).InsertRow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GrowLog/InsertRow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrowLogServer).InsertRow(ctx, req.(*TimeSeriesDatum))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrowLog_InsertRows_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GrowLogServer).InsertRows(&growLogInsertRowsServer{stream})
}

type GrowLog_InsertRowsServer interface {
	SendAndClose(*empty.Empty) error
	Recv() (*TimeSeriesDatum, error)
	grpc.ServerStream
}

type growLogInsertRowsServer struct {
	grpc.ServerStream
}

func (x *growLogInsertRowsServer) SendAndClose(m *empty.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *growLogInsertRowsServer) Recv() (*TimeSeriesDatum, error) {
	m := new(TimeSeriesDatum)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GrowLog_Select_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Filter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GrowLogServer).Select(m, &growLogSelectServer{stream})
}

type GrowLog_SelectServer interface {
	Send(*DataPoint) error
	grpc.ServerStream
}

type growLogSelectServer struct {
	grpc.ServerStream
}

func (x *growLogSelectServer) Send(m *DataPoint) error {
	return x.ServerStream.SendMsg(m)
}

// GrowLog_ServiceDesc is the grpc.ServiceDesc for GrowLog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrowLog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GrowLog",
	HandlerType: (*GrowLogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _GrowLog_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _GrowLog_Login_Handler,
		},
		{
			MethodName: "InsertRow",
			Handler:    _GrowLog_InsertRow_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InsertRows",
			Handler:       _GrowLog_InsertRows_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Select",
			Handler:       _GrowLog_Select_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/growlog.proto",
}
